# Generated by Django 5.2.6 on 2025-09-21 02:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام دسته')),
                ('slug', models.SlugField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان محصول')),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='تصویر محصول')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('product_type', models.CharField(choices=[('bulk', 'فله\u200cای'), ('packaged', 'بسته\u200cبندی')], default='bulk', max_length=10, verbose_name='نوع محصول')),
                ('price_per_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='قیمت هر کیلو')),
                ('package_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='وزن بسته (گرم)')),
                ('package_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='قیمت بسته')),
                ('available', models.BooleanField(default=True, verbose_name='موجودی')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category')),
            ],
        ),
    ]
